<a href="https://colab.research.google.com/github/preetamjumech/DL_DNN_from_Scratch/blob/main/Preetam_Saha_26_09_2022_Passenger_Dataset_DNN_target_long().ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/airline_passenger_satisfaction.csv")
df.head()

ID  Gender  Age Customer Type Type of Travel     Class  Flight Distance  \
0   1    Male   48    First-time       Business  Business              821   
1   2  Female   35     Returning       Business  Business              821   
2   3    Male   41     Returning       Business  Business              853   
3   4    Male   50     Returning       Business  Business             1905   
4   5  Female   49     Returning       Business  Business             3470   

   Departure Delay  Arrival Delay  Departure and Arrival Time Convenience  \
0                2            5.0                                       3   
1               26           39.0                                       2   
2                0            0.0                                       4   
3                0            0.0                                       2   
4                0            1.0                                       3   

   ...  On-board Service  Seat Comfort  Leg Room Service  Cleanliness  \
0  ...                 3             5                 2            5   
1  ...                 5             4                 5            5   
2  ...                 3             5                 3            5   
3  ...                 5             5                 5            4   
4  ...                 3             4                 4            5   

   Food and Drink  In-flight Service  In-flight Wifi Service  \
0               5                  5                       3   
1               3                  5                       2   
2               5                  3                       4   
3               4                  5                       2   
4               4                  3                       3   

   In-flight Entertainment  Baggage Handling             Satisfaction  
0                        5                 5  Neutral or Dissatisfied  
1                        5                 5                Satisfied  
2                        3                 3                Satisfied  
3                        5                 5                Satisfied  
4                        3                 3                Satisfied  

[5 rows x 24 columns]

In [ ]:
df.shape

(129880, 24)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129880 entries, 0 to 129879
Data columns (total 24 columns):
 #   Column                                  Non-Null Count   Dtype  
---  ------                                  --------------   -----  
 0   ID                                      129880 non-null  int64  
 1   Gender                                  129880 non-null  object 
 2   Age                                     129880 non-null  int64  
 3   Customer Type                           129880 non-null  object 
 4   Type of Travel                          129880 non-null  object 
 5   Class                                   129880 non-null  object 
 6   Flight Distance                         129880 non-null  int64  
 7   Departure Delay                         129880 non-null  int64  
 8   Arrival Delay                           129487 non-null  float64
 9   Departure and Arrival Time Convenience  129880 non-null  int64  
 10  Ease of Online Booking                  1298

In [ ]:
df.isna().sum()

ID                                          0
Gender                                      0
Age                                         0
Customer Type                               0
Type of Travel                              0
Class                                       0
Flight Distance                             0
Departure Delay                             0
Arrival Delay                             393
Departure and Arrival Time Convenience      0
Ease of Online Booking                      0
Check-in Service                            0
Online Boarding                             0
Gate Location                               0
On-board Service                            0
Seat Comfort                                0
Leg Room Service                            0
Cleanliness                                 0
Food and Drink                              0
In-flight Service                           0
In-flight Wifi Service                      0
In-flight Entertainment           

In [ ]:
df.dropna(axis = 0,inplace = True)

In [ ]:
df.shape

(129487, 24)

In [ ]:
df.drop(["ID"],axis=1,inplace=True)

In [ ]:
y = df.Satisfaction

In [ ]:
y

0         Neutral or Dissatisfied
1                       Satisfied
2                       Satisfied
3                       Satisfied
4                       Satisfied
                   ...           
129875    Neutral or Dissatisfied
129876    Neutral or Dissatisfied
129877    Neutral or Dissatisfied
129878                  Satisfied
129879    Neutral or Dissatisfied
Name: Satisfaction, Length: 129487, dtype: object

In [ ]:
y = y.map({"Neutral or Dissatisfied":0,"Satisfied":1})
y

0         0
1         1
2         1
3         1
4         1
         ..
129875    0
129876    0
129877    0
129878    1
129879    0
Name: Satisfaction, Length: 129487, dtype: int64

In [ ]:
cat=['Gender','Customer Type', 'Type of Travel', 'Class']

In [ ]:
cat_tab=df[cat]

In [ ]:
cat_tab

Gender Customer Type Type of Travel         Class
0         Male    First-time       Business      Business
1       Female     Returning       Business      Business
2         Male     Returning       Business      Business
3         Male     Returning       Business      Business
4       Female     Returning       Business      Business
...        ...           ...            ...           ...
129875    Male     Returning       Personal  Economy Plus
129876    Male     Returning       Personal  Economy Plus
129877    Male     Returning       Personal  Economy Plus
129878    Male     Returning       Personal  Economy Plus
129879  Female     Returning       Personal  Economy Plus

[129487 rows x 4 columns]

In [ ]:
cat_tab=pd.get_dummies(cat_tab,drop_first=True)

In [ ]:
cat_tab

Gender_Male  Customer Type_Returning  Type of Travel_Personal  \
0                 1                        0                        0   
1                 0                        1                        0   
2                 1                        1                        0   
3                 1                        1                        0   
4                 0                        1                        0   
...             ...                      ...                      ...   
129875            1                        1                        1   
129876            1                        1                        1   
129877            1                        1                        1   
129878            1                        1                        1   
129879            0                        1                        1   

        Class_Economy  Class_Economy Plus  
0                   0                   0  
1                   0                   0  
2                   0                   0  
3                   0                   0  
4                   0                   0  
...               ...                 ...  
129875              0                   1  
129876              0                   1  
129877              0                   1  
129878              0                   1  
129879              0                   1  

[129487 rows x 5 columns]

In [ ]:
cont=[i for i in df.columns if i not in cat]

In [ ]:
cont.remove("Satisfaction")

In [ ]:
cont

['Age',
 'Flight Distance',
 'Departure Delay',
 'Arrival Delay',
 'Departure and Arrival Time Convenience',
 'Ease of Online Booking',
 'Check-in Service',
 'Online Boarding',
 'Gate Location',
 'On-board Service',
 'Seat Comfort',
 'Leg Room Service',
 'Cleanliness',
 'Food and Drink',
 'In-flight Service',
 'In-flight Wifi Service',
 'In-flight Entertainment',
 'Baggage Handling']

In [ ]:
X=pd.concat([cat_tab,df[cont]],axis=1)

In [ ]:
X.shape

(129487, 23)

In [ ]:
y.shape

(129487,)

In [ ]:
import torch,torchsummary
import torch.nn as nn
import torch.nn.functional as F 
from torch.utils.data import DataLoader,TensorDataset 
from torch.optim import Adam,RMSprop

In [ ]:
X.values

array([[1., 0., 0., ..., 3., 5., 5.],
       [0., 1., 0., ..., 2., 5., 5.],
       [1., 1., 0., ..., 4., 3., 3.],
       ...,
       [1., 1., 1., ..., 2., 3., 5.],
       [1., 1., 1., ..., 5., 3., 5.],
       [0., 1., 1., ..., 3., 2., 1.]])

In [ ]:
y.values

array([0, 1, 1, ..., 0, 1, 0])

In [ ]:
X = torch.tensor(X.values)
y=torch.Tensor(y.values)

In [ ]:
X

tensor([[1., 0., 0.,  ..., 3., 5., 5.],
        [0., 1., 0.,  ..., 2., 5., 5.],
        [1., 1., 0.,  ..., 4., 3., 3.],
        ...,
        [1., 1., 1.,  ..., 2., 3., 5.],
        [1., 1., 1.,  ..., 5., 3., 5.],
        [0., 1., 1.,  ..., 3., 2., 1.]], dtype=torch.float64)

In [ ]:
#model=nn.Sequential(nn.Linear(X.shape[1],3),nn.Sigmoid(),nn.BatchNorm1d(3),nn.Dropout1d(0.5),nn.Linear(3,1),nn.Sigmoid())


In [ ]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.3)

In [ ]:
X_train.shape

torch.Size([90640, 23])

In [ ]:
X_test.shape

torch.Size([38847, 23])

In [ ]:
y_train.shape

torch.Size([90640])

In [ ]:
#y_train=y_train.reshape(-1,1)

In [ ]:
y_train.shape

torch.Size([90640])

In [ ]:
y_train

tensor([1., 0., 0.,  ..., 1., 0., 0.])

In [ ]:
#y_test = y_test.reshape(-1,1)

In [ ]:
X_train.sum(dim=1).sum()

tensor(1.1855e+08, dtype=torch.float64)

In [ ]:
train_loader = DataLoader(TensorDataset(X_train.float(),y_train),
                                       batch_size=64,shuffle = True)

test_loader = DataLoader(TensorDataset(X_test.float(),y_test),
                                      batch_size = 64,shuffle = False)

In [ ]:
class DNN_MNIST(nn.Module):
  def __init__(self):
    super(DNN_MNIST,self).__init__()

    self.h1 = nn.Linear(in_features=23, out_features = 512)
    self.h2 = nn.Linear(in_features=512, out_features = 256)
    self.h3 = nn.Linear(in_features=256, out_features = 128)
    self.h4 = nn.Linear(in_features=128, out_features = 64)
    self.out = nn.Linear(in_features=64, out_features = 2)
    self.bn1 = nn.BatchNorm1d(num_features=512)
    self.bn2 = nn.BatchNorm1d(num_features=256)
    self.bn3 = nn.BatchNorm1d(num_features=128)
    self.dropout = nn.Dropout(p=0.4)

  def forward(self,x):
    x = F.relu(self.h1(x))
    x = self.bn1(x)
    x = self.dropout(x)

    x = F.relu(self.h2(x))
    x = self.bn2(x)
    x = self.dropout(x)

    x = F.relu(self.h3(x))
    x = self.bn3(x)
    x = self.dropout(x)

    x = F.relu(self.h4(x))
    x = self.dropout(x)

    x = self.out(x)
    return x

In [ ]:
dnn_model = DNN_MNIST()

In [ ]:
list(dnn_model.parameters())

[Parameter containing:
 tensor([[ 0.1235,  0.0860,  0.0027,  ..., -0.1981, -0.0894, -0.1292],
         [-0.1138, -0.0854, -0.0386,  ...,  0.2005,  0.1933,  0.1857],
         [-0.0288,  0.0261, -0.1581,  ..., -0.1960, -0.1778,  0.1849],
         ...,
         [-0.0842, -0.1437,  0.1424,  ...,  0.1796, -0.0715,  0.0857],
         [ 0.0376, -0.1086,  0.1857,  ...,  0.1265, -0.0774,  0.0070],
         [ 0.1576,  0.1994, -0.0792,  ..., -0.0868,  0.1106, -0.1679]],
        requires_grad=True), Parameter containing:
 tensor([ 3.2932e-02,  1.8715e-01, -1.2266e-01, -1.0933e-01, -2.8011e-02,
          1.3273e-01, -1.4093e-01,  3.5686e-03,  1.2247e-01,  3.7326e-02,
         -8.7191e-02,  6.0583e-03, -5.5020e-02, -1.8837e-02, -3.2059e-02,
         -8.7280e-03, -2.7460e-02, -2.0224e-02,  1.9115e-01, -1.9902e-01,
         -1.1578e-01, -1.2501e-02,  6.8978e-02,  5.5058e-02,  9.6639e-02,
         -8.3409e-02, -1.8137e-01,  1.5933e-01, -1.5511e-01,  1.3343e-01,
          1.6726e-01,  9.1757e-03,  3.743

In [ ]:
opt = Adam(dnn_model.parameters(),lr=0.001)

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [ ]:
dnn_model = dnn_model.to(device)

In [ ]:
#y_train.int()

In [ ]:
n_epochs=6
for epoch in range(n_epochs):
  training_loss=0.0
  
  for batch, target in train_loader:
    batch = batch.float().to("cuda")
    target = target.to("cuda")
    #print(target)
    opt.zero_grad()
    output=dnn_model(batch)
    # print(target)
    loss=F.cross_entropy(output, target.long())
    # print(loss)
    loss.backward()
    opt.step()
    training_loss+=loss.item()
    
  val_loss=0.0
  for val_batch,val_target in test_loader:
    val_batch = val_batch.to(device)
    val_target = val_target.type(torch.LongTensor)
    val_target = val_target.to(device)
    pred=dnn_model(val_batch)
    loss_val=F.cross_entropy(pred,val_target)
    val_loss+=loss_val.item()
  if(epoch+1)%5==0:
    print(f"Training loss:{training_loss}")
    print(f"Test loss:{val_loss}")
  

Training loss:373.5493873357773
Test loss:152.07396049052477
